name: Build Wrapper

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup env
      run: sudo apt install unzip -y
    - name: Fetch Pojlib Release
      id: fetch-latest-release-pojlib
      uses: gregziegan/fetch-latest-release@v2.0.0
      with:
        repo_path: QuestCraftPlusPlus/Pojlib
    - name: Download Pojlib
      run: |
        wget https://github.com/QuestCraftPlusPlus/Pojlib/releases/download/test/lib-release.aar
        cp -f lib-release.aar $GITHUB_WORKSPACE/Assets/Plugins/Android
    - uses: actions/cache@v2
      with:
        path: QCXR-XR-Wrapper/Library
        key: Library-QCXR-XR-Wrapper-Android
        restore-keys: |
          Library-QCXR-XR-Wrapper-
          Library-
    - name: Unity - Builder
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        allowDirtyBuild: true
        customImage: 'unityci/editor:2021.3.22f1-base-0'
        targetPlatform: Android
        androidExportType: 'androidPackage'
        androidTargetSdkVersion: '32'
        androidKeystoreName: user.keystore
        androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
        androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      uses: game-ci/unity-builder@v2.2.0
    - uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
